server {
    listen 80;
    root /app/www;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
    }
}